import csv
import io
import os
import smtplib
import asyncio
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.base import MIMEBase
from email import encoders


# ─── CSV Generation ───────────────────────────────────────────────────────────

_HEADERS = [
    "Source", "Broker / Agent Name", "Key Person", "Key Person Title", "Phone", "Email", "Address",
    "Property Name", "Price", "Config", "Area (sqft)", "RERA", "Website / URL",
    "Rating", "Reviews",
]


def _row(source: str, item: dict) -> list:
    return [
        source,
        item.get("name", ""),
        item.get("key_person", ""),
        item.get("key_person_title", ""),
        item.get("phone", ""),
        item.get("email", ""),
        item.get("address", ""),
        item.get("property_name") or item.get("title") or item.get("name") or "",
        item.get("price", ""),
        item.get("config", ""),
        item.get("area_sqft", ""),
        item.get("rera", ""),
        item.get("website") or item.get("maps_url") or item.get("url") or "",
        item.get("rating", ""),
        item.get("reviews", ""),
    ]


def _maps_row(item: dict) -> list:
    return [
        "Google Maps",
        item.get("name", ""),
        item.get("key_person", ""),
        item.get("key_person_title", ""),
        item.get("phone", ""),
        item.get("email", ""),
        item.get("address", ""),
        "",  # property_name
        "",  # price
        ", ".join(item.get("categories", [])),  # config column repurposed
        "",  # area_sqft
        "",  # rera
        item.get("website") or item.get("maps_url") or "",
        item.get("rating", ""),
        item.get("reviews", ""),
    ]


def _jd_row(item: dict) -> list:
    return [
        "JustDial",
        item.get("name", ""),
        item.get("key_person", ""),
        item.get("key_person_title", ""),
        item.get("phone", ""),
        item.get("email", ""),
        item.get("address", ""),
        "",
        "",
        ", ".join(item.get("categories", [])),
        "",
        "",
        item.get("website") or item.get("maps_url") or "",
        item.get("rating", ""),
        item.get("reviews", ""),
    ]


def generate_csv(unified_brokers: list, raw_results: dict = None) -> str:
    output = io.StringIO()
    writer = csv.writer(output)
    writer.writerow(_HEADERS)

    if unified_brokers:
        # Unified path: single clean list from Groq, no source labels
        for item in unified_brokers:
            writer.writerow(_row("", item))
    elif raw_results:
        # Fallback: per-source raw data
        for item in raw_results.get("google_maps", {}).get("data", []):
            writer.writerow(_maps_row(item))
        for item in raw_results.get("99acres", {}).get("data", []):
            writer.writerow(_row("99acres", item))
        for item in raw_results.get("magicbricks", {}).get("data", []):
            writer.writerow(_row("MagicBricks", item))
        for item in raw_results.get("justdial", {}).get("data", []):
            writer.writerow(_jd_row(item))

    return output.getvalue()


# ─── Email Send ───────────────────────────────────────────────────────────────

def _send_sync(to_email: str, csv_bytes: bytes, filename: str, project_name: str):
    host = os.getenv("SMTP_HOST", "smtp.gmail.com")
    port = int(os.getenv("SMTP_PORT", "587"))
    user = os.getenv("SMTP_USER", "")
    password = os.getenv("SMTP_PASS", "")

    if not user or not password:
        raise ValueError("SMTP_USER and SMTP_PASS must be set in .env to send emails.")

    msg = MIMEMultipart()
    msg["From"] = user
    msg["To"] = to_email
    msg["Subject"] = f"Broker Intelligence Report – {project_name}"

    body = (
        f"Hi,\n\nPlease find the broker intelligence report for '{project_name}' attached as a CSV.\n\n"
        "This report was generated by Builder Broker Intelligence.\n"
    )
    msg.attach(MIMEText(body, "plain"))

    part = MIMEBase("application", "octet-stream")
    part.set_payload(csv_bytes)
    encoders.encode_base64(part)
    part.add_header("Content-Disposition", f'attachment; filename="{filename}"')
    msg.attach(part)

    with smtplib.SMTP(host, port) as server:
        server.ehlo()
        server.starttls()
        server.login(user, password)
        server.send_message(msg)


async def send_csv_email(to_email: str, csv_content: str, project_name: str):
    safe_name = "".join(c if c.isalnum() or c in " _-" else "_" for c in project_name)
    filename = f"brokers_{safe_name}.csv"
    csv_bytes = csv_content.encode("utf-8-sig")  # utf-8-sig adds BOM so Excel opens correctly
    await asyncio.get_event_loop().run_in_executor(
        None, _send_sync, to_email, csv_bytes, filename, project_name
    )
